
import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/cupertino.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:social_app/constants/api_constants.dart';
import 'package:social_app/di/app_providers.dart';
import 'package:social_app/src/data/repository/remote/remote_repository.dart';
import 'package:social_app/src/presentation/notifier/streaming/state/stream_state.dart';
import 'package:social_app/utils/loader_util/loading_dialog.dart';

import '../../../../constants/app_constants.dart';
import '../../../../utils/snackbar_widget.dart';
import '../../../data/repository/local/local_repository.dart';
part 'streaming_notifier.g.dart';

@riverpod
class StreamNotifier extends _$StreamNotifier {
  RemoteRepository? remoteRepository;

  @override
  StreamState build(String id) {
    remoteRepository = ref.read(remoteRepositoryProvider);
    state = StreamState();
    if(id.isEmpty){
      generateToken();
    }
    return StreamState(liveUser: id.isEmpty,chanel: id);
  }

  void generateToken() async{
    WidgetsBinding.instance.addPostFrameCallback((_) async{

      AppConstants.globalKey.currentContext!.loading.show();

      var res = await remoteRepository?.generateToken(channel: AppConstants.userModel!.userId);
      AppConstants.globalKey.currentContext!.loading.hide();


      if(res!.success){
        state = state.copyWith(token:"007eJxTYGia/D9kuaG13J0Z0kbcr/v3OE0pcbr07tTk5uXfGt56fpZSYEixMDA1TjK2TEwzTzVJMje0TDFItjRNSjFMNU9ONk8x4cxfk94QyMhw8NANVkYGCATxJRjMzJLSjEwNU03SjBMTTU1NLRItUlJSTRMZGACw+Ccv");
        if(state.liveUser){
          state = state.copyWith(chanel:AppConstants.userModel!.userId);
        }
        setUpEngine();

        showToast(AppConstants.globalKey.currentContext!,res.message);
      }else{
        showToast(AppConstants.globalKey.currentContext!,res.message,success: false);
      }


    });

  }

  void setUpEngine() async{
    state = state.copyWith(engine: createAgoraRtcEngine());


    await state.engine?.initialize(const RtcEngineContext(
      appId: ApiConstants.appId,
      channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
    ));


    await state.engine?.joinChannel(
      // Join a channel using a temporary token and channel name
      token: state.token,
      channelId: state.chanel,
      options: const ChannelMediaOptions(
          // Set user role to clientRoleBroadcaster (broadcaster) or clientRoleAudience (audience)
          clientRoleType: ClientRoleType.clientRoleBroadcaster,

      )
      ,
      uid: AppConstants.userModel!.userId.hashCode, // When you set uid to 0, a user name is randomly generated by the engine
    );

    state.engine?.registerEventHandler(
      RtcEngineEventHandler(
        // Occurs when the local user joins the channel successfully
        onJoinChannelSuccess: (RtcConnection connection, int elapsed) {
          debugPrint("local user ${connection.localUid} joined");
          state = state.copyWith(localUserId: connection.localUid!);
        },
        // Occurs when a remote user join the channel
        onUserJoined: (RtcConnection connection, int remoteUid, int elapsed) {
          debugPrint("remote user $remoteUid joined");
          state = state.copyWith(localUserId: remoteUid);
        },
        // Occurs when a remote user leaves the channel
        onUserOffline: (RtcConnection connection, int remoteUid,
            UserOfflineReasonType reason) {
          debugPrint("remote user $remoteUid left channel");

        },
      ),
    );


  }

}