name: Fastlane Deploy to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: 'stable'
          cache: true
      - name: Set up Flutter
        run: 
#          # Clone Flutter SDK
#          git clone https://github.com/flutter/flutter.git -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter/bin/flutter doctor # Ensure flutter is available in the PATH

      - name: Create local.properties
        run: |
          echo "sdk.dir=${HOME}/Android/Sdk" > android/local.properties
          echo "flutter.sdk=${GITHUB_WORKSPACE}/flutter" >> android/local.properties
          echo "flutter.buildMode=debug" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties

      - name: Install Dependencies
        run: |
          flutter/bin/flutter clean   
          flutter/bin/flutter pub upgrade  
          flutter/bin/flutter pub run build_runner build --delete-conflicting-outputs

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler --user-install
          gem install fastlane -NV --user-install
          gem install fastlane-plugin-firebase_app_distribution --user-install
          sudo npm install -g firebase-tools

      - name: Print Environment Variables
        run: printenv

      - name: Run Fastlane deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Add your Firebase token as a GitHub secret
        run: |
          cd android # Navigate to the android directory
          fastlane android deploy
