name: iOS TestFlight Deployment

on:
  push:
    branches:
      - ios  # Change this to your deployment branch

jobs:
  deploy:
    name: Build & Upload to TestFlight
    runs-on: macos-latest  # Ensure macOS runner for iOS builds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: "3.27.1"
            channel: 'stable'
            cache: true

      - name: Get Packages
        run: flutter pub get


      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          rm Podfile.lock
          pod install --repo-update # Ensure pods are correctly installed

      - name: Install Fastlane
        run: |
          brew install fastlane  # Install fastlane via Homebrew (this is the recommended method for macOS)
      - name: Print Environment Variables
        run: |
            echo "APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}"
            echo "APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}"
            echo "APP_STORE_TEAM_ID: ${{ secrets.APP_STORE_TEAM_ID }}"
            echo "APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}"
            echo "APP_NAME: ${{ secrets.APP_NAME }}"
            echo "FASTLANE_USER: ${{ secrets.FASTLANE_APPLE_ID }}"
            echo "FASTLANE_AUTH_KEY: ${{ secrets.FASTLANE_AUTH_KEY }}"
            echo "MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}"
#      - name: Decrypt and Save App Store Auth Key
#        env:
#          FASTLANE_AUTH_KEY: ${{ secrets.FASTLANE_AUTH_KEY }}
#        run: |
#          mkdir -p ~/kasim
#          echo "$FASTLANE_AUTH_KEY" | base64 --decode > ~/fastlane/AuthKey.p8

#      - name: Unlock Keychain
#        run: |
#          security unlock-keychain -p "${{ secrets.MATCH_PASSWORD }}" /Users/runner/Library/Keychains/login.keychain-db
      - name: Build & Upload to TestFlight
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_TEAM_ID: ${{ secrets.APP_STORE_TEAM_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APP_NAME: ${{ secrets.APP_NAME }}
          FASTLANE_USER: ${{ secrets.FASTLANE_APPLE_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane ios beta