name: iOS TestFlight Deployment

on:
  push:
    branches: [ ios ]
jobs:
  deploy:
    name: Build & Upload to TestFlight
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install Bundler
        run: |
          gem install bundler

      - name: Install Dependencies via Bundler
        run: |
          cd ios
          bundle install

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: 'stable'
          cache: true

      - name: Get Packages
        run: |
          flutter clean
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          rm Podfile.lock
          pod install 

      - name: Print environment variables
        run: |
          echo "APPLE_KEY_CONTENT=${{ secrets.APPLE_KEY_CONTENT }}"
          echo "APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}"
          echo "TEMP_KEYCHAIN_PASSWORD=${{ secrets.TEMP_KEYCHAIN_PASSWORD }}"
          echo "APPLE_ISSUER_ID=${{ secrets.APPLE_ISSUER_ID }}"
          echo "APP_IDENTIFIER=${{ secrets.APP_IDENTIFIER }}"
          echo "TEMP_KEYCHAIN_USER=${{ secrets.TEMP_KEYCHAIN_USER }}"
          echo "FASTLANE_USER=${{ secrets.FASTLANE_APPLE_ID }}"
          echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}"
          echo "FASTLANE_VERBOSE=${{ secrets.FASTLANE_VERBOSE }}"


      - name: Build & Upload to TestFlight
        env:
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          FASTLANE_USER: ${{ secrets.FASTLANE_APPLE_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_VERBOSE: true


        run: |
          cd ios
          fastlane match appstore --readonly
          fastlane ios beta --verbose
