name: Mobile App Deployment

on:
  push:
    branches:
      - new-branch  # Change this to your deployment branch
  workflow_dispatch:

jobs:
  deploy_ios:
    name: Build & Upload iOS to TestFlight
    runs-on: macos-latest  # Required for iOS builds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: 'stable'
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          rm Podfile.lock
          pod install --repo-update

      - name: Install Fastlane
        run: brew install fastlane

      - name: Build & Upload to TestFlight
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_TEAM_ID: ${{ secrets.APP_STORE_TEAM_ID }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APP_NAME: ${{ secrets.APP_NAME }}
          FASTLANE_USER: ${{ secrets.FASTLANE_APPLE_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane ios beta

  deploy_android:
    name: Build & Upload Android to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: 'stable'
          cache: true

      - name: Create local.properties
        run: |
          echo "sdk.dir=${HOME}/Android/Sdk" > android/local.properties
          echo "flutter.sdk=${GITHUB_WORKSPACE}/flutter" >> android/local.properties
          echo "flutter.buildMode=debug" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties

      - name: Install Dependencies
        run: |
          flutter clean   
          flutter pub upgrade  
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler --user-install
          gem install fastlane -NV --user-install
          gem install fastlane-plugin-firebase_app_distribution --user-install
          sudo npm install -g firebase-tools

      - name: Run Fastlane Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd android
          fastlane android deploy
